tcpk: tcpk.o
	gcc tcpk.o -o tcpk

tcps: tcps.o
	gcc tcps.o -o tcps

udps: udps.o
	gcc udps.o -o udps

udpk: udpk.o
	gcc udpk.o -o udpk

udpk.o: udpk.c
	gcc -c udpk.c

udps.o: udps.c
	gcc -c udps.c

tcps.o: tcps.c
	gcc -c tcps.c

tcpk.o: tcpk.c
	gcc -c tcpk.c


